services:
  web:
    image: nginx:1.23
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-data:/var/www/html
    networks:
      - app-network
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure 
  db:
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdbname
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager  
      restart_policy:
        condition: on-failure 

volumes:
  nginx-conf:
  nginx-data:
  postgres-data:

networks:
  app-network:
    driver: overlay
