services:
  app:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins_net
    restart: always

volumes:
  jenkins_home:
    driver: local

networks:
  jenkins_net:
    driver: bridge
